#!/usr/bin/env python3
"""Embed an MSL source file as a deterministic C string include."""

from __future__ import annotations

import argparse
import pathlib


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("input", type=pathlib.Path)
    parser.add_argument("output", type=pathlib.Path)
    args = parser.parse_args()

    source = args.input.read_text(encoding="utf-8")
    encoded = source.encode("utf-8") + b"\0"
    lines = []
    for offset in range(0, len(encoded), 24):
        lines.append(
            "    " + ", ".join(str(value) for value in encoded[offset : offset + 24])
        )
    content = (
        "/* Generated by tools/embed_metal_source.py; do not edit. */\n"
        "static const unsigned char kipp_metal_source[] = {\n"
        + ",\n".join(lines)
        + "\n};\n"
    )
    args.output.write_text(content, encoding="utf-8")


if __name__ == "__main__":
    main()
