#!/usr/bin/env python3
"""Generate compact Unicode property ranges for Kipp's Qwen pre-tokenizer."""

from __future__ import annotations

import argparse
import pathlib
import unicodedata


def ranges_for(predicate: object) -> list[tuple[int, int]]:
    ranges: list[tuple[int, int]] = []
    start: int | None = None
    previous = -1
    for codepoint in range(0x110000):
        if predicate(codepoint):
            if start is None:
                start = codepoint
            previous = codepoint
        elif start is not None:
            ranges.append((start, previous))
            start = None
    if start is not None:
        ranges.append((start, previous))
    return ranges


def render_table(name: str, ranges: list[tuple[int, int]]) -> str:
    lines = [
        f"#define KIPP_UNICODE_{name.upper()}_RANGE_COUNT {len(ranges)}u",
        f"static const unicode_range kipp_unicode_{name}_ranges[] = {{",
    ]
    for first, last in ranges:
        lines.append(f"    {{UINT32_C(0x{first:06x}), UINT32_C(0x{last:06x})}},")
    lines.append("};")
    return "\n".join(lines)


def canonical_decompositions() -> list[tuple[int, tuple[int, ...]]]:
    entries: list[tuple[int, tuple[int, ...]]] = []
    for codepoint in range(0x110000):
        if 0xAC00 <= codepoint <= 0xD7A3:
            continue  # Handled algorithmically by the native NFC implementation.
        decomposition = unicodedata.decomposition(chr(codepoint))
        if not decomposition or decomposition.startswith("<"):
            continue
        parts = tuple(int(part, 16) for part in decomposition.split())
        if len(parts) not in (1, 2):
            raise ValueError(
                f"unexpected canonical decomposition length for U+{codepoint:04X}"
            )
        entries.append((codepoint, parts))
    return entries


def render_normalization_tables() -> str:
    decompositions = canonical_decompositions()
    combining = [
        (codepoint, unicodedata.combining(chr(codepoint)))
        for codepoint in range(0x110000)
        if unicodedata.combining(chr(codepoint))
    ]
    compositions: list[tuple[int, int, int]] = []
    for codepoint, parts in decompositions:
        if len(parts) != 2:
            continue
        source = "".join(chr(part) for part in parts)
        if unicodedata.normalize("NFC", source) == chr(codepoint):
            compositions.append((parts[0], parts[1], codepoint))
    compositions.sort(key=lambda entry: (entry[0], entry[1]))

    lines = [
        f"#define KIPP_UNICODE_DECOMPOSITION_COUNT {len(decompositions)}u",
        "static const unicode_decomposition kipp_unicode_decompositions[] = {",
    ]
    for codepoint, parts in decompositions:
        first = parts[0]
        second = parts[1] if len(parts) == 2 else 0
        lines.append(
            f"    {{UINT32_C(0x{codepoint:06x}), UINT32_C(0x{first:06x}), "
            f"UINT32_C(0x{second:06x}), {len(parts)}u}},"
        )
    lines.extend(
        [
            "};",
            "",
            f"#define KIPP_UNICODE_COMBINING_COUNT {len(combining)}u",
            "static const unicode_combining kipp_unicode_combining_classes[] = {",
        ]
    )
    for codepoint, combining_class in combining:
        lines.append(
            f"    {{UINT32_C(0x{codepoint:06x}), {combining_class}u}},"
        )
    lines.extend(
        [
            "};",
            "",
            f"#define KIPP_UNICODE_COMPOSITION_COUNT {len(compositions)}u",
            "static const unicode_composition kipp_unicode_compositions[] = {",
        ]
    )
    for first, second, result in compositions:
        lines.append(
            f"    {{UINT32_C(0x{first:06x}), UINT32_C(0x{second:06x}), "
            f"UINT32_C(0x{result:06x})}},"
        )
    lines.append("};")
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("output", type=pathlib.Path)
    args = parser.parse_args()

    letter = ranges_for(
        lambda codepoint: unicodedata.category(chr(codepoint)).startswith("L")
    )
    number = ranges_for(
        lambda codepoint: unicodedata.category(chr(codepoint)).startswith("N")
    )
    space = ranges_for(lambda codepoint: chr(codepoint).isspace())

    content = "\n".join(
        [
            "/* Generated by tools/generate_unicode_tables.py.",
            f" * Unicode database: {unicodedata.unidata_version}",
            " * Do not edit by hand.",
            " */",
            "",
            render_table("letter", letter),
            "",
            render_table("number", number),
            "",
            render_table("space", space),
            "",
            render_normalization_tables(),
            "",
        ]
    )
    args.output.write_text(content, encoding="utf-8")


if __name__ == "__main__":
    main()
